apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "microservice.name" . }}
  labels:
    {{- include "microservice.labels" . | nindent 4 }}
data:
  requirements.txt: |
    Flask
    jsonify

  app.py: |
    from flask import Flask, jsonify
    import os

    app = Flask(__name__)

    @app.route('/version', methods=['GET'])
    def get_version():
        version = os.getenv("VERSION", "unknown")
        return jsonify({"version": version})

    if __name__ == '__main__':
        app.run(host='0.0.0.0', port=80)
